### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException when loading Wisconsin shapefile from tutorial

### ISSUE THREAD

**Issue by happyjack27** [happyjack27/autoredistrict#172]
Hi Kevin,

I've been trying to get Auto-Redistrict running and have been getting ArrayIndexOutOfBoundsException errors while trying to load the same Wisconsin data seen in your Tutorial 1 video. I've copied the output during use - any ideas on what's going wrong?

Thanks,

~Steve

D:\Redistricter\autoredistrict>run-windows.bat

D:\Redistricter\autoredistrict>D:\Desktop\jre-8u121-windows-x64.tar\jre-8u121-windows-x64\jre1.8.0_121\bin\java -jar autoredistrict.jar
jre version: 1.8.0_121
creating binomial cache...
binomial cache created.
binomial_as_normal n:1001.0 k:500.0 p:0.51 ret:0.7468185279694906
0.7468185279694906
binomial_as_normal n:1001.0 k:500.0 p:0.52 ret:0.902888853982651
0.902888853982651
binomial_as_normal n:1001.0 k:500.0 p:0.55 ret:0.9993399261462654
0.9993399261462654
pct to hide: 0.0
pct to hide: 0.0
no history found! []
no history found! []
no history found! []
Processing wards_111312_ed_110612.shp...
GEOID10  NAME  ASM  SEN  CON  WARD_FIPS  COUSUBFP  MCD_NAME  MCD_FIPS  CNTY_NAME  CNTY_FIPS  JVTD2  STR_WARDS  SUPER_DIST  SPLIT  PERSONS  WHITE  BLACK  HISPANIC  ASIAN  AMINDIAN  PISLAND  OTHER  OTHERMLT  PERSONS18  WHITE18  BLACK18  HISPANIC18  ASIAN18  AMINDIAN18  PISLAND18  OTHER18  OTHERMLT18  PRES_TOT12  PRES_REP12  PRES_DEM12  PRES_CON12  PRESIND112  PRESIND212  PRESIND312  PRESIND412  PRESIND512  PRESIND612  PRESSCAT12  SEN_TOT12  SEN_REP12  SEN_DEM12  SEN_IND112  SEN_IND212  SEN_IND312  SEN_CON_12  SEN_SCAT12  CON_TOT_12  CON_REP_12  CON_DEM_12  CON_IND_12  CON_SCAT12  SS_TOT_12  SS_REP_12  SS_DEM_12  SS_IND_12  SS_SCAT_12  ASM_TOT_12  ASM_REP_12  ASM_DEM_12  ASM_IND112  ASM_SCAT12  ASM_DEM212  ASM_IND212  ASM_REP212  DA_TOT_12  DA_REP_12  DA_DEM_12  DA_IND_12  DA_SCAT_12  DA_DEM2_12  CTV
The shape type of this files is POLYGON
eofexception
GEOID10  NAME  ASM  SEN  CON  WARD_FIPS  COUSUBFP  MCD_NAME  MCD_FIPS  CNTY_NAME  CNTY_FIPS  JVTD2  STR_WARDS  SUPER_DIST  SPLIT  PERSONS  WHITE  BLACK  HISPANIC  ASIAN  AMINDIAN  PISLAND  OTHER  OTHERMLT  PERSONS18  WHITE18  BLACK18  HISPANIC18  ASIAN18  AMINDIAN18  PISLAND18  OTHER18  OTHERMLT18  PRES_TOT12  PRES_REP12  PRES_DEM12  PRES_CON12  PRESIND112  PRESIND212  PRESIND312  PRESIND412  PRESIND512  PRESIND612  PRESSCAT12  SEN_TOT12  SEN_REP12  SEN_DEM12  SEN_IND112  SEN_IND212  SEN_IND312  SEN_CON_12  SEN_SCAT12  CON_TOT_12  CON_REP_12  CON_DEM_12  CON_IND_12  CON_SCAT12  SS_TOT_12  SS_REP_12  SS_DEM_12  SS_IND_12  SS_SCAT_12  ASM_TOT_12  ASM_REP_12  ASM_DEM_12  ASM_IND112  ASM_SCAT12  ASM_DEM212  ASM_IND212  ASM_REP212  DA_TOT_12  DA_REP_12  DA_DEM_12  DA_IND_12  DA_SCAT_12  DA_DEM2_12  CTV
Total shapes read: 6634
6634 precincts loaded.
294822.7681,225108.63770000078
773288.2905000001,734398.1289000008
Initializing wards...
vertex_xs: 462341
vertex_all: 793482
unpaired edges: 133533
paired edges: 676382
percent: 83.513%
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................connecting islands...
total 6634 vtds
found island 6597 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found island 1 vtds
found 38 islands...
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
found closest island: 0
294822.8800186874,225108.5146302756
773288.1593136118,734397.9365163806
filling combo boxes...
population..
pkey..
setDistrictColumn hush?false
Ready.
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at java.util.Vector.get(Vector.java:748)
        at ui.MainFrame.setSubstituteColumns(MainFrame.java:3382)
        at ui.MainFrame.finishLoadingGeography(MainFrame.java:2958)
        at ui.MainFrame$OpenShapeFileThread.run(MainFrame.java:2005)
 ----------- Mar 19, 2017 10:29:22 PM: INSTRUCTION SLEEP 2000
 ----------- Mar 19, 2017 10:29:24 PM: INSTRUCTION DONE

**Comment by happyjack27** [comment]
was using an old binary.
