### ISSUE TITLE
ArrayIndexOutOfBoundsException Error

### ISSUE THREAD

**Issue by franciscooooooo** [happyjack27/autoredistrict#199]
When I tried to load shapefile I got the error below. My shapefile has over 60000 features.

ex java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
        at java.util.Vector.get(Unknown Source)
        at ui.MainFrame.getMinMaxXY(MainFrame.java:2885)
        at ui.MainFrame.finishLoadingGeography(MainFrame.java:2917)
        at ui.MainFrame$OpenShapeFileThread.run(MainFrame.java:2013)
java.lang.NullPointerException
        at ui.MainFrame.setElectionColumns(MainFrame.java:3276)
        at ui.MainFrame.trySetGroupColumns(MainFrame.java:6903)
        at ui.MainFrame$OpenShapeFileThread.run(MainFrame.java:2031)
Exception in thread "Thread-3" java.lang.NullPointerException
        at ui.MainFrame.trySetGroupColumns(MainFrame.java:6923)
        at ui.MainFrame$OpenShapeFileThread.run(MainFrame.java:2031)

**Comment by happyjack27** [comment]
it should be able to handle 60k features fine.

the error is not related to the number of features.

i'd need a copy of the shapefile to diagnose.

**Comment by happyjack27** [comment]
...and i'm not sure the error is really an error.

did the shapefile load?

are you having any problems using the software?
